name: vsearch-plus
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.10
  - openjdk >=17
  - cxx-compiler
  - make
  - autoconf
  - automake
  - pkg-config
  - zlib
  - bzip2
  - wget
